---
all:
  hosts:
    nexus-01:
      ansible_host: 130.193.53.249
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: user
    ansible_ssh_private_key_file: /home/user/ssh_keys/id_rsa